name: Deploy frontend application

on:
  push:
    branches:
      - "main"
      - "feature/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            awesomekid/234-deploylab-frontend:latest
            awesomekid/234-deploylab-frontend:${{ github.ref_name | replace('/', '-') }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            BRANCH="${{ github.ref_name | replace('/', '-') }}"
            COMPOSE_FILE="docker-compose-$([ "${{ github.ref }}" == refs/heads/main* ] && echo "default" || echo "prod").yml"
            
            # Copy compose file
            mkdir -p "/home/ubuntu/frontend-${BRANCH}"
            scp -o StrictHostKeyChecking=no ${COMPOSE_FILE} ${{ secrets.HOST_USER_NAME }}@${{ secrets.HOST_SERVER }}:/home/ubuntu/frontend-${BRANCH}/docker-compose.yml
            
            # Deploy
            cd "/home/ubuntu/frontend-${BRANCH}"
            docker compose -p "frontend-${BRANCH}" down
            docker compose -p "frontend-${BRANCH}" pull
            docker compose -p "frontend-${BRANCH}" up -d